/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Categoria;
import Logica.Compuesta;
import Logica.Fabrica;
import Logica.ISistema;
import Manejadores.ManejadorCategoria;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *-
 * @author leandro
 */
public class AltaCategoria extends javax.swing.JInternalFrame {

    private ISistema IS;
    /**
     * Creates new form AltaCategoria
     */
    
    
    public AltaCategoria() {
        initComponents();
        
        Fabrica fabrica = Fabrica.getInstance();
        IS = fabrica.getISistema(); 
        ManejadorCategoria categorias = ManejadorCategoria.getInstance();
        
        //-------------------------------------------------------------------
        //          PERSISTENCIA
        //-------------------------------------------------------------------
        
        //categorias.cargarDatos();
        
        
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorias");
        categorias.crearArbol(raiz);
        DefaultTreeModel modelo = new DefaultTreeModel(raiz);
        this.arbol.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        entradaNombre = new javax.swing.JTextField();
        botonConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        primerNivel = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioSimple = new javax.swing.JRadioButton();
        radioCompuesta = new javax.swing.JRadioButton();

        jLabel1.setText("Nombre");

        botonConfirmar.setText("Confirmar");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Alta Categoria");

        primerNivel.setText("Primer Nivel");
        primerNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerNivelActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(arbol);

        jLabel2.setText("Seleccione nombre del padre");

        jLabel3.setText("Tipo de Categoria");

        opciones.add(radioSimple);
        radioSimple.setText("Simple");

        opciones.add(radioCompuesta);
        radioCompuesta.setText("Compuesta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(primerNivel)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioSimple)
                        .addGap(18, 18, 18)
                        .addComponent(radioCompuesta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(botonConfirmar)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(primerNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radioSimple)
                    .addComponent(radioCompuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConfirmar)
                    .addComponent(btnCancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void primerNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerNivelActionPerformed
        // TODO add your handling code here:
        if(primerNivel.isSelected()){
            arbol.setEnabled(false);
        }else
            arbol.setEnabled(true);
    }//GEN-LAST:event_primerNivelActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        if("".equals(entradaNombre.getText())){
            JOptionPane.showMessageDialog(null, "Ingrese un nombre","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            if(!radioSimple.isSelected() && !radioCompuesta.isSelected()){
                JOptionPane.showMessageDialog(null, "Seleccione tipo de categoria","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                if(primerNivel.isSelected()){
                    if(radioSimple.isSelected()){
                        boolean retorno;
                        retorno = IS.altaCategoria(entradaNombre.getText(), "", "Simple", false);
                        if(retorno){
                            JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                        }else{
                            JOptionPane.showMessageDialog(null, "El padre no admite otras categorias","Error",JOptionPane.ERROR_MESSAGE); 
                        }
                        ManejadorCategoria categorias = ManejadorCategoria.getInstance();
                        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorias");
                        categorias.crearArbol(raiz);
                        DefaultTreeModel modelo = new DefaultTreeModel(raiz);
                        this.arbol.setModel(modelo);
                    }else{
                        boolean retorno;
                        retorno = IS.altaCategoria(entradaNombre.getText(), "", "Compuesta", false);
                        if(retorno){
                            JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                        }else{
                            JOptionPane.showMessageDialog(null, "El padre no admite otras categorias","Error",JOptionPane.ERROR_MESSAGE); 
                        }
                        ManejadorCategoria categorias = ManejadorCategoria.getInstance();
                        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorias");
                        categorias.crearArbol(raiz);
                        DefaultTreeModel modelo = new DefaultTreeModel(raiz);
                        this.arbol.setModel(modelo);
                    }
                }else{
                    if(arbol.getSelectionPath() == null){
                        JOptionPane.showMessageDialog(null, "Seleccione el padre","Error",JOptionPane.ERROR_MESSAGE);
                    }else{
                        String[] separador = arbol.getSelectionPath().toString().split(",");
                        int tamano = separador.length;
                        String aux = separador[tamano-1];

                        aux = aux.substring(1);

                        separador = aux.split("]");
                        aux = separador[0];
                        //System.out.println(aux);
                        if(radioSimple.isSelected()){
                            boolean retorno;
                            retorno = IS.altaCategoria(entradaNombre.getText(), aux, "Simple", false);
                            if(retorno){
                               JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                            }else{
                                JOptionPane.showMessageDialog(null, "El padre no admite otras categorias","Error",JOptionPane.ERROR_MESSAGE); 
                            }
                            ManejadorCategoria categorias = ManejadorCategoria.getInstance();
                            DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorias");
                            categorias.crearArbol(raiz);
                            DefaultTreeModel modelo = new DefaultTreeModel(raiz);
                            this.arbol.setModel(modelo);
                        }else{
                            boolean retorno;
                            retorno = IS.altaCategoria(entradaNombre.getText(), aux, "Compuesta", false);
                            if(retorno){
                                JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                            }else{
                                JOptionPane.showMessageDialog(null, "El padre no admite otras categorias","Error",JOptionPane.ERROR_MESSAGE); 
                            }
                            ManejadorCategoria categorias = ManejadorCategoria.getInstance();
                            DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorias");
                            categorias.crearArbol(raiz);
                            DefaultTreeModel modelo = new DefaultTreeModel(raiz);
                            this.arbol.setModel(modelo);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_botonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.ButtonGroup opciones;
    private javax.swing.JCheckBox primerNivel;
    private javax.swing.JRadioButton radioCompuesta;
    private javax.swing.JRadioButton radioSimple;
    // End of variables declaration//GEN-END:variables
}
